### ISSUE TITLE
CaptureImageJpeg No Such File or Directory

### ISSUE THREAD

**Issue by thnk2wn** [unosquare/raspberryio#208]
**Describe the bug**
Using `Pi.Init<BootstrapWiringPi>();` followed by `byte[] imageBytes = Pi.Camera.CaptureImageJpeg(1024, 768);` and I get the following error:

<pre>
02:14:36 ERR] Error taking picture
System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Swan.ProcessRunner.<>c__DisplayClass7_0.<RunProcessAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Unosquare.RaspberryIO.Camera.CameraController.CaptureImageAsync(CameraStillSettings settings, CancellationToken ct)
   at Unosquare.RaspberryIO.Camera.CameraController.CaptureImageJpeg(Int32 width, Int32 height)
</pre>

**To Reproduce**
1. Match environment details as shown in the `Devices` section.
2. Run code as listed in above description

**Expected behavior**
Picture bytes to be obtained.

**Screenshots**

**Devices**
* Unosquare.Raspberry.IO Version="0.27.0"
* Unosquare.WiringPi Version="0.5.0"
* 3.1.1-buster-slim-arm32v7 docker image (running privileged)
* OS Raspbian GNU/Linux 10 (buster)
* Raspberry Pi 4 Model B Rev 1.1 (4GB RAM)

**Additional context**
The camera is enabled and I was able to test it via `raspistill -o image.jpg`. Is there something else I have to install or configure on the device to use this? Ideas?

**Comment by thnk2wn** [comment]
I'm assuming I need to adjust the creation of my container with potential volume mounts or Dockerfile steps like:

````
RUN apt-get install libraspberrypi-bin -y
RUN usermod -a -G video root
````

Not sure what all dependencies this library has for the camera in terms of file / directory access, permissions etc. to account for when running containerized but I can look at the source. From the error though it looks like it's just shelling out to another process rather than a direct embedded library calls so maybe going through Unosquare just for this one camera method call is overkill.

**Comment by thnk2wn** [comment]
I was able to make it work by adding `ENV PATH="/opt/vc/bin:${PATH}"` to the `Dockerfile` and adding `-v /opt/vc/bin:/opt/vc/bin` to `docker run`. 

The complete docker run looks like below.

````bash
docker run \
    --privileged \
    -v /opt/vc/lib:/opt/vc/lib \
    -v /opt/vc/bin:/opt/vc/bin \
    -v /home/pi/camera-output:/home/pi/camera-output \
    -d \
    --name $name \
    $username/$name:latest
````

I was assuming the camera module was taking more of a library approach similar to https://github.com/techyian/MMALSharp but as it's shelling to `raspistill` I can probably achieve similar results doing so more directly if not using the MMAL approach though other features of unosquare may be helpful for other features.
